// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback _Nonnull free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureResultU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureResultI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureResultU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureResultI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureResultU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureResultI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureResultU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureResultI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureResultF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureResultF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureResultRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureResultVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD0
typedef void (*UniffiCallbackInterfaceEventListenerMethod0)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD1
typedef void (*UniffiCallbackInterfaceEventListenerMethod1)(uint64_t, RustBuffer, uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD2
typedef void (*UniffiCallbackInterfaceEventListenerMethod2)(uint64_t, RustBuffer, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD3
typedef void (*UniffiCallbackInterfaceEventListenerMethod3)(uint64_t, uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD4
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD4
typedef void (*UniffiCallbackInterfaceEventListenerMethod4)(uint64_t, uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EVENT_LISTENER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EVENT_LISTENER
typedef struct UniffiVTableCallbackInterfaceEventListener {
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
    UniffiCallbackInterfaceClone _Nonnull uniffiClone;
    UniffiCallbackInterfaceEventListenerMethod0 _Nonnull onRepositoryChanged;
    UniffiCallbackInterfaceEventListenerMethod1 _Nonnull onGitCommand;
    UniffiCallbackInterfaceEventListenerMethod2 _Nonnull onWatcherError;
    UniffiCallbackInterfaceEventListenerMethod3 _Nonnull onTerminalData;
    UniffiCallbackInterfaceEventListenerMethod4 _Nonnull onTerminalExit;
} UniffiVTableCallbackInterfaceEventListener;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_INIT_CALLBACK_VTABLE_EVENTLISTENER
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_INIT_CALLBACK_VTABLE_EVENTLISTENER
void uniffi_deathpush_ffi_fn_init_callback_vtable_eventlistener(const UniffiVTableCallbackInterfaceEventListener* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_CREATE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_CREATE_SESSION
void uniffi_deathpush_ffi_fn_func_create_session(RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DESTROY_SESSION
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DESTROY_SESSION
void uniffi_deathpush_ffi_fn_func_destroy_session(RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_RESOLVED_ENVIRONMENT
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_RESOLVED_ENVIRONMENT
RustBuffer uniffi_deathpush_ffi_fn_func_get_resolved_environment(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_INITIALIZE
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_INITIALIZE
void uniffi_deathpush_ffi_fn_func_initialize(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_REGISTER_EVENT_LISTENER
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_REGISTER_EVENT_LISTENER
void uniffi_deathpush_ffi_fn_func_register_event_listener(uint64_t listener, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_FILE_BLAME
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_FILE_BLAME
RustBuffer uniffi_deathpush_ffi_fn_func_get_file_blame(RustBuffer session_id, RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_FILE_LOG
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_FILE_LOG
RustBuffer uniffi_deathpush_ffi_fn_func_get_file_log(RustBuffer session_id, RustBuffer path, uint32_t skip, uint32_t limit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_LAST_COMMIT_INFO
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_LAST_COMMIT_INFO
RustBuffer uniffi_deathpush_ffi_fn_func_get_last_commit_info(RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_CHECKOUT_BRANCH
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_CHECKOUT_BRANCH
RustBuffer uniffi_deathpush_ffi_fn_func_checkout_branch(RustBuffer session_id, RustBuffer name, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_CREATE_BRANCH
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_CREATE_BRANCH
RustBuffer uniffi_deathpush_ffi_fn_func_create_branch(RustBuffer session_id, RustBuffer name, RustBuffer start_point, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DELETE_BRANCH
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DELETE_BRANCH
void uniffi_deathpush_ffi_fn_func_delete_branch(RustBuffer session_id, RustBuffer name, int8_t force, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DELETE_REMOTE_BRANCH
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DELETE_REMOTE_BRANCH
void uniffi_deathpush_ffi_fn_func_delete_remote_branch(RustBuffer session_id, RustBuffer remote, RustBuffer name, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_LIST_BRANCHES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_LIST_BRANCHES
RustBuffer uniffi_deathpush_ffi_fn_func_list_branches(RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_RENAME_BRANCH
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_RENAME_BRANCH
RustBuffer uniffi_deathpush_ffi_fn_func_rename_branch(RustBuffer session_id, RustBuffer old_name, RustBuffer new_name, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_COMMIT
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_COMMIT
RustBuffer uniffi_deathpush_ffi_fn_func_commit(RustBuffer session_id, RustBuffer message, int8_t amend, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_GIT_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_GIT_CONFIG
RustBuffer uniffi_deathpush_ffi_fn_func_get_git_config(RustBuffer key, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_SET_GIT_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_SET_GIT_CONFIG
void uniffi_deathpush_ffi_fn_func_set_git_config(RustBuffer key, RustBuffer value, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_FUZZY_FIND_FILES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_FUZZY_FIND_FILES
RustBuffer uniffi_deathpush_ffi_fn_func_fuzzy_find_files(RustBuffer session_id, RustBuffer query, uint32_t max_results, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_LIST_DIRECTORY
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_LIST_DIRECTORY
RustBuffer uniffi_deathpush_ffi_fn_func_list_directory(RustBuffer session_id, RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_READ_FILE_CONTENT
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_READ_FILE_CONTENT
RustBuffer uniffi_deathpush_ffi_fn_func_read_file_content(RustBuffer session_id, RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_SEARCH_FILE_CONTENTS
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_SEARCH_FILE_CONTENTS
RustBuffer uniffi_deathpush_ffi_fn_func_search_file_contents(RustBuffer session_id, RustBuffer query, uint32_t max_results, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_ADD_TO_GITIGNORE
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_ADD_TO_GITIGNORE
RustBuffer uniffi_deathpush_ffi_fn_func_add_to_gitignore(RustBuffer session_id, RustBuffer pattern, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_COPY_ENTRIES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_COPY_ENTRIES
void uniffi_deathpush_ffi_fn_func_copy_entries(RustBuffer session_id, RustBuffer sources, RustBuffer destination_dir, RustBuffer on_conflict, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_CREATE_DIRECTORY
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_CREATE_DIRECTORY
void uniffi_deathpush_ffi_fn_func_create_directory(RustBuffer session_id, RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DELETE_FILE
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DELETE_FILE
RustBuffer uniffi_deathpush_ffi_fn_func_delete_file(RustBuffer session_id, RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DELETE_FILES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DELETE_FILES
RustBuffer uniffi_deathpush_ffi_fn_func_delete_files(RustBuffer session_id, RustBuffer paths, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DUPLICATE_ENTRY
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DUPLICATE_ENTRY
RustBuffer uniffi_deathpush_ffi_fn_func_duplicate_entry(RustBuffer session_id, RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_IMPORT_FILES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_IMPORT_FILES
void uniffi_deathpush_ffi_fn_func_import_files(RustBuffer session_id, RustBuffer sources, RustBuffer destination_dir, RustBuffer on_conflict, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_MOVE_ENTRIES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_MOVE_ENTRIES
void uniffi_deathpush_ffi_fn_func_move_entries(RustBuffer session_id, RustBuffer sources, RustBuffer destination_dir, RustBuffer on_conflict, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_OPEN_IN_EDITOR
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_OPEN_IN_EDITOR
void uniffi_deathpush_ffi_fn_func_open_in_editor(RustBuffer session_id, RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_RENAME_ENTRY
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_RENAME_ENTRY
void uniffi_deathpush_ffi_fn_func_rename_entry(RustBuffer session_id, RustBuffer old_path, RustBuffer new_name, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_REVEAL_IN_FILE_MANAGER
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_REVEAL_IN_FILE_MANAGER
void uniffi_deathpush_ffi_fn_func_reveal_in_file_manager(RustBuffer session_id, RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_WRITE_FILE
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_WRITE_FILE
void uniffi_deathpush_ffi_fn_func_write_file(RustBuffer session_id, RustBuffer path, RustBuffer content, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_CHERRY_PICK
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_CHERRY_PICK
RustBuffer uniffi_deathpush_ffi_fn_func_cherry_pick(RustBuffer session_id, RustBuffer commit_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_CLONE_REPOSITORY
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_CLONE_REPOSITORY
RustBuffer uniffi_deathpush_ffi_fn_func_clone_repository(RustBuffer session_id, RustBuffer url, RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_INIT_REPOSITORY
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_INIT_REPOSITORY
RustBuffer uniffi_deathpush_ffi_fn_func_init_repository(RustBuffer session_id, RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_MERGE_ABORT
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_MERGE_ABORT
RustBuffer uniffi_deathpush_ffi_fn_func_merge_abort(RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_MERGE_BRANCH
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_MERGE_BRANCH
RustBuffer uniffi_deathpush_ffi_fn_func_merge_branch(RustBuffer session_id, RustBuffer name, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_MERGE_CONTINUE
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_MERGE_CONTINUE
RustBuffer uniffi_deathpush_ffi_fn_func_merge_continue(RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_REBASE_ABORT
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_REBASE_ABORT
RustBuffer uniffi_deathpush_ffi_fn_func_rebase_abort(RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_REBASE_BRANCH
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_REBASE_BRANCH
RustBuffer uniffi_deathpush_ffi_fn_func_rebase_branch(RustBuffer session_id, RustBuffer name, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_REBASE_CONTINUE
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_REBASE_CONTINUE
RustBuffer uniffi_deathpush_ffi_fn_func_rebase_continue(RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_REBASE_SKIP
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_REBASE_SKIP
RustBuffer uniffi_deathpush_ffi_fn_func_rebase_skip(RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_RESET_TO_COMMIT
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_RESET_TO_COMMIT
RustBuffer uniffi_deathpush_ffi_fn_func_reset_to_commit(RustBuffer session_id, RustBuffer id, RustBuffer mode, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_COMMIT_DETAIL
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_COMMIT_DETAIL
RustBuffer uniffi_deathpush_ffi_fn_func_get_commit_detail(RustBuffer session_id, RustBuffer commit_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_COMMIT_FILE_DIFF
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_COMMIT_FILE_DIFF
RustBuffer uniffi_deathpush_ffi_fn_func_get_commit_file_diff(RustBuffer session_id, RustBuffer commit_id, RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_COMMIT_LOG
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_COMMIT_LOG
RustBuffer uniffi_deathpush_ffi_fn_func_get_commit_log(RustBuffer session_id, uint32_t skip, uint32_t limit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_FETCH
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_FETCH
RustBuffer uniffi_deathpush_ffi_fn_func_fetch(RustBuffer session_id, RustBuffer remote, int8_t prune, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_PULL
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_PULL
RustBuffer uniffi_deathpush_ffi_fn_func_pull(RustBuffer session_id, RustBuffer remote, RustBuffer branch, int8_t rebase, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_PUSH
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_PUSH
RustBuffer uniffi_deathpush_ffi_fn_func_push(RustBuffer session_id, RustBuffer remote, RustBuffer branch, int8_t force, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DETECT_WORKTREES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DETECT_WORKTREES
RustBuffer uniffi_deathpush_ffi_fn_func_detect_worktrees(RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DISCOVER_REPOSITORIES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DISCOVER_REPOSITORIES
RustBuffer uniffi_deathpush_ffi_fn_func_discover_repositories(RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_REPO_BRANCH
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_REPO_BRANCH
RustBuffer uniffi_deathpush_ffi_fn_func_get_repo_branch(RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_OPEN_REPOSITORY
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_OPEN_REPOSITORY
RustBuffer uniffi_deathpush_ffi_fn_func_open_repository(RustBuffer session_id, RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_SCAN_PROJECTS_DIRECTORY
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_SCAN_PROJECTS_DIRECTORY
RustBuffer uniffi_deathpush_ffi_fn_func_scan_projects_directory(RustBuffer path, uint32_t depth, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DISCARD_CHANGES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DISCARD_CHANGES
RustBuffer uniffi_deathpush_ffi_fn_func_discard_changes(RustBuffer session_id, RustBuffer paths, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DISCARD_HUNK
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DISCARD_HUNK
RustBuffer uniffi_deathpush_ffi_fn_func_discard_hunk(RustBuffer session_id, RustBuffer path, uint32_t hunk_index, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_FILE_HUNKS
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_FILE_HUNKS
RustBuffer uniffi_deathpush_ffi_fn_func_get_file_hunks(RustBuffer session_id, RustBuffer path, int8_t staged, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STAGE_ALL
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STAGE_ALL
RustBuffer uniffi_deathpush_ffi_fn_func_stage_all(RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STAGE_FILES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STAGE_FILES
RustBuffer uniffi_deathpush_ffi_fn_func_stage_files(RustBuffer session_id, RustBuffer paths, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STAGE_HUNK
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STAGE_HUNK
RustBuffer uniffi_deathpush_ffi_fn_func_stage_hunk(RustBuffer session_id, RustBuffer path, uint32_t hunk_index, int8_t staged, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STAGE_LINES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STAGE_LINES
RustBuffer uniffi_deathpush_ffi_fn_func_stage_lines(RustBuffer session_id, RustBuffer path, uint32_t hunk_index, uint32_t line_start, uint32_t line_end, int8_t staged, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_UNSTAGE_ALL
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_UNSTAGE_ALL
RustBuffer uniffi_deathpush_ffi_fn_func_unstage_all(RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_UNSTAGE_FILES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_UNSTAGE_FILES
RustBuffer uniffi_deathpush_ffi_fn_func_unstage_files(RustBuffer session_id, RustBuffer paths, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_LAST_COMMIT_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_LAST_COMMIT_MESSAGE
RustBuffer uniffi_deathpush_ffi_fn_func_get_last_commit_message(RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STASH_APPLY
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STASH_APPLY
RustBuffer uniffi_deathpush_ffi_fn_func_stash_apply(RustBuffer session_id, uint32_t index, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STASH_DROP
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STASH_DROP
RustBuffer uniffi_deathpush_ffi_fn_func_stash_drop(RustBuffer session_id, uint32_t index, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STASH_LIST
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STASH_LIST
RustBuffer uniffi_deathpush_ffi_fn_func_stash_list(RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STASH_POP
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STASH_POP
RustBuffer uniffi_deathpush_ffi_fn_func_stash_pop(RustBuffer session_id, uint32_t index, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STASH_SAVE
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STASH_SAVE
RustBuffer uniffi_deathpush_ffi_fn_func_stash_save(RustBuffer session_id, RustBuffer message, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STASH_SAVE_INCLUDE_UNTRACKED
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STASH_SAVE_INCLUDE_UNTRACKED
RustBuffer uniffi_deathpush_ffi_fn_func_stash_save_include_untracked(RustBuffer session_id, RustBuffer message, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STASH_SAVE_STAGED
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STASH_SAVE_STAGED
RustBuffer uniffi_deathpush_ffi_fn_func_stash_save_staged(RustBuffer session_id, RustBuffer message, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STASH_SHOW
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_STASH_SHOW
RustBuffer uniffi_deathpush_ffi_fn_func_stash_show(RustBuffer session_id, uint32_t index, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_UNDO_LAST_COMMIT
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_UNDO_LAST_COMMIT
RustBuffer uniffi_deathpush_ffi_fn_func_undo_last_commit(RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_FILE_DIFF
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_FILE_DIFF
RustBuffer uniffi_deathpush_ffi_fn_func_get_file_diff(RustBuffer session_id, RustBuffer path, int8_t staged, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_STATUS
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_GET_STATUS
RustBuffer uniffi_deathpush_ffi_fn_func_get_status(RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_CREATE_TAG
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_CREATE_TAG
RustBuffer uniffi_deathpush_ffi_fn_func_create_tag(RustBuffer session_id, RustBuffer name, RustBuffer message, RustBuffer target, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DELETE_REMOTE_TAG
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DELETE_REMOTE_TAG
void uniffi_deathpush_ffi_fn_func_delete_remote_tag(RustBuffer session_id, RustBuffer remote, RustBuffer name, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DELETE_TAG
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_DELETE_TAG
RustBuffer uniffi_deathpush_ffi_fn_func_delete_tag(RustBuffer session_id, RustBuffer name, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_LIST_TAGS
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_LIST_TAGS
RustBuffer uniffi_deathpush_ffi_fn_func_list_tags(RustBuffer session_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_PUSH_TAG
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_PUSH_TAG
void uniffi_deathpush_ffi_fn_func_push_tag(RustBuffer session_id, RustBuffer remote, RustBuffer tag, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_TERMINAL_FOREGROUND_PROCESS
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_TERMINAL_FOREGROUND_PROCESS
RustBuffer uniffi_deathpush_ffi_fn_func_terminal_foreground_process(uint64_t terminal_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_TERMINAL_KILL
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_TERMINAL_KILL
void uniffi_deathpush_ffi_fn_func_terminal_kill(uint64_t terminal_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_TERMINAL_RESIZE
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_TERMINAL_RESIZE
void uniffi_deathpush_ffi_fn_func_terminal_resize(uint64_t terminal_id, uint16_t cols, uint16_t rows, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_TERMINAL_SPAWN
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_TERMINAL_SPAWN
RustBuffer uniffi_deathpush_ffi_fn_func_terminal_spawn(RustBuffer session_id, uint16_t cols, uint16_t rows, RustBuffer shell_path, RustBuffer shell_args, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_TERMINAL_WRITE
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_FN_FUNC_TERMINAL_WRITE
void uniffi_deathpush_ffi_fn_func_terminal_write(uint64_t terminal_id, RustBuffer data, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_deathpush_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_deathpush_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUSTBUFFER_FREE
void ffi_deathpush_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_deathpush_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_U8
void ffi_deathpush_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_U8
void ffi_deathpush_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_U8
void ffi_deathpush_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_deathpush_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_I8
void ffi_deathpush_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_I8
void ffi_deathpush_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_I8
void ffi_deathpush_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_deathpush_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_U16
void ffi_deathpush_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_U16
void ffi_deathpush_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_U16
void ffi_deathpush_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_deathpush_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_I16
void ffi_deathpush_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_I16
void ffi_deathpush_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_I16
void ffi_deathpush_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_deathpush_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_U32
void ffi_deathpush_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_U32
void ffi_deathpush_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_U32
void ffi_deathpush_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_deathpush_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_I32
void ffi_deathpush_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_I32
void ffi_deathpush_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_I32
void ffi_deathpush_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_deathpush_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_U64
void ffi_deathpush_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_U64
void ffi_deathpush_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_U64
void ffi_deathpush_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_deathpush_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_I64
void ffi_deathpush_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_I64
void ffi_deathpush_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_I64
void ffi_deathpush_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_deathpush_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_F32
void ffi_deathpush_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_F32
void ffi_deathpush_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_F32
void ffi_deathpush_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_deathpush_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_F64
void ffi_deathpush_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_F64
void ffi_deathpush_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_F64
void ffi_deathpush_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_deathpush_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_deathpush_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_deathpush_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_deathpush_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_deathpush_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_POLL_VOID
void ffi_deathpush_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_deathpush_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_FREE_VOID
void ffi_deathpush_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_deathpush_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_CREATE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_CREATE_SESSION
uint16_t uniffi_deathpush_ffi_checksum_func_create_session(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DESTROY_SESSION
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DESTROY_SESSION
uint16_t uniffi_deathpush_ffi_checksum_func_destroy_session(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_RESOLVED_ENVIRONMENT
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_RESOLVED_ENVIRONMENT
uint16_t uniffi_deathpush_ffi_checksum_func_get_resolved_environment(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_INITIALIZE
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_INITIALIZE
uint16_t uniffi_deathpush_ffi_checksum_func_initialize(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_REGISTER_EVENT_LISTENER
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_REGISTER_EVENT_LISTENER
uint16_t uniffi_deathpush_ffi_checksum_func_register_event_listener(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_FILE_BLAME
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_FILE_BLAME
uint16_t uniffi_deathpush_ffi_checksum_func_get_file_blame(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_FILE_LOG
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_FILE_LOG
uint16_t uniffi_deathpush_ffi_checksum_func_get_file_log(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_LAST_COMMIT_INFO
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_LAST_COMMIT_INFO
uint16_t uniffi_deathpush_ffi_checksum_func_get_last_commit_info(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_CHECKOUT_BRANCH
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_CHECKOUT_BRANCH
uint16_t uniffi_deathpush_ffi_checksum_func_checkout_branch(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_CREATE_BRANCH
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_CREATE_BRANCH
uint16_t uniffi_deathpush_ffi_checksum_func_create_branch(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DELETE_BRANCH
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DELETE_BRANCH
uint16_t uniffi_deathpush_ffi_checksum_func_delete_branch(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DELETE_REMOTE_BRANCH
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DELETE_REMOTE_BRANCH
uint16_t uniffi_deathpush_ffi_checksum_func_delete_remote_branch(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_LIST_BRANCHES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_LIST_BRANCHES
uint16_t uniffi_deathpush_ffi_checksum_func_list_branches(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_RENAME_BRANCH
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_RENAME_BRANCH
uint16_t uniffi_deathpush_ffi_checksum_func_rename_branch(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_COMMIT
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_COMMIT
uint16_t uniffi_deathpush_ffi_checksum_func_commit(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_GIT_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_GIT_CONFIG
uint16_t uniffi_deathpush_ffi_checksum_func_get_git_config(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_SET_GIT_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_SET_GIT_CONFIG
uint16_t uniffi_deathpush_ffi_checksum_func_set_git_config(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_FUZZY_FIND_FILES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_FUZZY_FIND_FILES
uint16_t uniffi_deathpush_ffi_checksum_func_fuzzy_find_files(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_LIST_DIRECTORY
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_LIST_DIRECTORY
uint16_t uniffi_deathpush_ffi_checksum_func_list_directory(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_READ_FILE_CONTENT
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_READ_FILE_CONTENT
uint16_t uniffi_deathpush_ffi_checksum_func_read_file_content(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_SEARCH_FILE_CONTENTS
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_SEARCH_FILE_CONTENTS
uint16_t uniffi_deathpush_ffi_checksum_func_search_file_contents(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_ADD_TO_GITIGNORE
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_ADD_TO_GITIGNORE
uint16_t uniffi_deathpush_ffi_checksum_func_add_to_gitignore(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_COPY_ENTRIES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_COPY_ENTRIES
uint16_t uniffi_deathpush_ffi_checksum_func_copy_entries(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_CREATE_DIRECTORY
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_CREATE_DIRECTORY
uint16_t uniffi_deathpush_ffi_checksum_func_create_directory(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DELETE_FILE
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DELETE_FILE
uint16_t uniffi_deathpush_ffi_checksum_func_delete_file(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DELETE_FILES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DELETE_FILES
uint16_t uniffi_deathpush_ffi_checksum_func_delete_files(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DUPLICATE_ENTRY
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DUPLICATE_ENTRY
uint16_t uniffi_deathpush_ffi_checksum_func_duplicate_entry(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_IMPORT_FILES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_IMPORT_FILES
uint16_t uniffi_deathpush_ffi_checksum_func_import_files(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_MOVE_ENTRIES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_MOVE_ENTRIES
uint16_t uniffi_deathpush_ffi_checksum_func_move_entries(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_OPEN_IN_EDITOR
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_OPEN_IN_EDITOR
uint16_t uniffi_deathpush_ffi_checksum_func_open_in_editor(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_RENAME_ENTRY
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_RENAME_ENTRY
uint16_t uniffi_deathpush_ffi_checksum_func_rename_entry(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_REVEAL_IN_FILE_MANAGER
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_REVEAL_IN_FILE_MANAGER
uint16_t uniffi_deathpush_ffi_checksum_func_reveal_in_file_manager(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_WRITE_FILE
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_WRITE_FILE
uint16_t uniffi_deathpush_ffi_checksum_func_write_file(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_CHERRY_PICK
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_CHERRY_PICK
uint16_t uniffi_deathpush_ffi_checksum_func_cherry_pick(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_CLONE_REPOSITORY
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_CLONE_REPOSITORY
uint16_t uniffi_deathpush_ffi_checksum_func_clone_repository(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_INIT_REPOSITORY
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_INIT_REPOSITORY
uint16_t uniffi_deathpush_ffi_checksum_func_init_repository(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_MERGE_ABORT
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_MERGE_ABORT
uint16_t uniffi_deathpush_ffi_checksum_func_merge_abort(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_MERGE_BRANCH
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_MERGE_BRANCH
uint16_t uniffi_deathpush_ffi_checksum_func_merge_branch(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_MERGE_CONTINUE
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_MERGE_CONTINUE
uint16_t uniffi_deathpush_ffi_checksum_func_merge_continue(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_REBASE_ABORT
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_REBASE_ABORT
uint16_t uniffi_deathpush_ffi_checksum_func_rebase_abort(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_REBASE_BRANCH
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_REBASE_BRANCH
uint16_t uniffi_deathpush_ffi_checksum_func_rebase_branch(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_REBASE_CONTINUE
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_REBASE_CONTINUE
uint16_t uniffi_deathpush_ffi_checksum_func_rebase_continue(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_REBASE_SKIP
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_REBASE_SKIP
uint16_t uniffi_deathpush_ffi_checksum_func_rebase_skip(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_RESET_TO_COMMIT
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_RESET_TO_COMMIT
uint16_t uniffi_deathpush_ffi_checksum_func_reset_to_commit(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_COMMIT_DETAIL
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_COMMIT_DETAIL
uint16_t uniffi_deathpush_ffi_checksum_func_get_commit_detail(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_COMMIT_FILE_DIFF
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_COMMIT_FILE_DIFF
uint16_t uniffi_deathpush_ffi_checksum_func_get_commit_file_diff(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_COMMIT_LOG
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_COMMIT_LOG
uint16_t uniffi_deathpush_ffi_checksum_func_get_commit_log(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_FETCH
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_FETCH
uint16_t uniffi_deathpush_ffi_checksum_func_fetch(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_PULL
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_PULL
uint16_t uniffi_deathpush_ffi_checksum_func_pull(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_PUSH
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_PUSH
uint16_t uniffi_deathpush_ffi_checksum_func_push(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DETECT_WORKTREES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DETECT_WORKTREES
uint16_t uniffi_deathpush_ffi_checksum_func_detect_worktrees(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DISCOVER_REPOSITORIES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DISCOVER_REPOSITORIES
uint16_t uniffi_deathpush_ffi_checksum_func_discover_repositories(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_REPO_BRANCH
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_REPO_BRANCH
uint16_t uniffi_deathpush_ffi_checksum_func_get_repo_branch(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_OPEN_REPOSITORY
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_OPEN_REPOSITORY
uint16_t uniffi_deathpush_ffi_checksum_func_open_repository(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_SCAN_PROJECTS_DIRECTORY
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_SCAN_PROJECTS_DIRECTORY
uint16_t uniffi_deathpush_ffi_checksum_func_scan_projects_directory(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DISCARD_CHANGES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DISCARD_CHANGES
uint16_t uniffi_deathpush_ffi_checksum_func_discard_changes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DISCARD_HUNK
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DISCARD_HUNK
uint16_t uniffi_deathpush_ffi_checksum_func_discard_hunk(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_FILE_HUNKS
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_FILE_HUNKS
uint16_t uniffi_deathpush_ffi_checksum_func_get_file_hunks(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STAGE_ALL
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STAGE_ALL
uint16_t uniffi_deathpush_ffi_checksum_func_stage_all(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STAGE_FILES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STAGE_FILES
uint16_t uniffi_deathpush_ffi_checksum_func_stage_files(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STAGE_HUNK
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STAGE_HUNK
uint16_t uniffi_deathpush_ffi_checksum_func_stage_hunk(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STAGE_LINES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STAGE_LINES
uint16_t uniffi_deathpush_ffi_checksum_func_stage_lines(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_UNSTAGE_ALL
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_UNSTAGE_ALL
uint16_t uniffi_deathpush_ffi_checksum_func_unstage_all(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_UNSTAGE_FILES
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_UNSTAGE_FILES
uint16_t uniffi_deathpush_ffi_checksum_func_unstage_files(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_LAST_COMMIT_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_LAST_COMMIT_MESSAGE
uint16_t uniffi_deathpush_ffi_checksum_func_get_last_commit_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STASH_APPLY
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STASH_APPLY
uint16_t uniffi_deathpush_ffi_checksum_func_stash_apply(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STASH_DROP
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STASH_DROP
uint16_t uniffi_deathpush_ffi_checksum_func_stash_drop(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STASH_LIST
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STASH_LIST
uint16_t uniffi_deathpush_ffi_checksum_func_stash_list(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STASH_POP
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STASH_POP
uint16_t uniffi_deathpush_ffi_checksum_func_stash_pop(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STASH_SAVE
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STASH_SAVE
uint16_t uniffi_deathpush_ffi_checksum_func_stash_save(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STASH_SAVE_INCLUDE_UNTRACKED
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STASH_SAVE_INCLUDE_UNTRACKED
uint16_t uniffi_deathpush_ffi_checksum_func_stash_save_include_untracked(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STASH_SAVE_STAGED
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STASH_SAVE_STAGED
uint16_t uniffi_deathpush_ffi_checksum_func_stash_save_staged(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STASH_SHOW
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_STASH_SHOW
uint16_t uniffi_deathpush_ffi_checksum_func_stash_show(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_UNDO_LAST_COMMIT
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_UNDO_LAST_COMMIT
uint16_t uniffi_deathpush_ffi_checksum_func_undo_last_commit(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_FILE_DIFF
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_FILE_DIFF
uint16_t uniffi_deathpush_ffi_checksum_func_get_file_diff(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_STATUS
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_GET_STATUS
uint16_t uniffi_deathpush_ffi_checksum_func_get_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_CREATE_TAG
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_CREATE_TAG
uint16_t uniffi_deathpush_ffi_checksum_func_create_tag(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DELETE_REMOTE_TAG
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DELETE_REMOTE_TAG
uint16_t uniffi_deathpush_ffi_checksum_func_delete_remote_tag(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DELETE_TAG
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_DELETE_TAG
uint16_t uniffi_deathpush_ffi_checksum_func_delete_tag(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_LIST_TAGS
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_LIST_TAGS
uint16_t uniffi_deathpush_ffi_checksum_func_list_tags(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_PUSH_TAG
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_PUSH_TAG
uint16_t uniffi_deathpush_ffi_checksum_func_push_tag(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_TERMINAL_FOREGROUND_PROCESS
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_TERMINAL_FOREGROUND_PROCESS
uint16_t uniffi_deathpush_ffi_checksum_func_terminal_foreground_process(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_TERMINAL_KILL
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_TERMINAL_KILL
uint16_t uniffi_deathpush_ffi_checksum_func_terminal_kill(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_TERMINAL_RESIZE
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_TERMINAL_RESIZE
uint16_t uniffi_deathpush_ffi_checksum_func_terminal_resize(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_TERMINAL_SPAWN
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_TERMINAL_SPAWN
uint16_t uniffi_deathpush_ffi_checksum_func_terminal_spawn(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_TERMINAL_WRITE
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_FUNC_TERMINAL_WRITE
uint16_t uniffi_deathpush_ffi_checksum_func_terminal_write(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_METHOD_EVENTLISTENER_ON_REPOSITORY_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_METHOD_EVENTLISTENER_ON_REPOSITORY_CHANGED
uint16_t uniffi_deathpush_ffi_checksum_method_eventlistener_on_repository_changed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_METHOD_EVENTLISTENER_ON_GIT_COMMAND
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_METHOD_EVENTLISTENER_ON_GIT_COMMAND
uint16_t uniffi_deathpush_ffi_checksum_method_eventlistener_on_git_command(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_METHOD_EVENTLISTENER_ON_WATCHER_ERROR
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_METHOD_EVENTLISTENER_ON_WATCHER_ERROR
uint16_t uniffi_deathpush_ffi_checksum_method_eventlistener_on_watcher_error(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_METHOD_EVENTLISTENER_ON_TERMINAL_DATA
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_METHOD_EVENTLISTENER_ON_TERMINAL_DATA
uint16_t uniffi_deathpush_ffi_checksum_method_eventlistener_on_terminal_data(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_METHOD_EVENTLISTENER_ON_TERMINAL_EXIT
#define UNIFFI_FFIDEF_UNIFFI_DEATHPUSH_FFI_CHECKSUM_METHOD_EVENTLISTENER_ON_TERMINAL_EXIT
uint16_t uniffi_deathpush_ffi_checksum_method_eventlistener_on_terminal_exit(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_DEATHPUSH_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_deathpush_ffi_uniffi_contract_version(void
    
);
#endif

